### ISSUE TITLE
PeopleViewer project cannot be open properly in Visual Studio

### ISSUE THREAD

**Issue by sfiri91** [jeremybytes/csharp-interfaces-resources#1]
Hello Mr. Jeremy,

first of all, thank you for your great Pluralsight course!

During exercising on my laptop, I encountered an error when I tried to open the **FutureProofing** Solution in Visual Studio. The root cause of the issue is the missing "profiles" property on the 10th line in the file: **csharp-interfaces-resources-main\net50\module2\before\FutureProofing\PeopleViewer\Properties\launchSettings.json**

Thank you!

With kind regards,

Sebastian

**Comment by sfiri91** [comment]
After removing that 1 mentioned curly brace in the file, the solution can be built successfully, but when I try to run it - the browser doesn't open automatically. As a workaround, I can manually open the browser and type: http://localhost:5000, but that's not of course the permanent solution.

**Comment by jeremybytes** [comment]
Thank you for reporting this. I have fixed the launchSettings.json file (removed an extra brace).
